# name: Code Writer

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
  schedule:
    - cron: "0 0 * * *"
  # - cron: "0 0 * * 1"

jobs:
  schedule:
    name: Check Repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch repos
        run: cd ./packages/codewriter && yarn install && yarn fetch-repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Lint JSON
        run: cd ./packages/codewriter && yarn jsonlint

      - name: Make PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: automated/json-updates
          delete-branch: true
          title: "[Automated] Updates for JSON payload"
          commit-message: "feat/Update JSON payload"
          reviewers: "ticklepoke"
          token: ${{ secrets.GH_TOKEN }}
