name: Continuous Integration

on: 
  pull_request:
    branches:
      - master
      - staging

jobs:
  buildAndTest:
    name: Build and Test (Client)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: cd ./packages/client && yarn install
      
      - name: Test
        run: cd ./packages/client &&  yarn test --watchAll=false
      
      - name: Lint
        run: cd ./packages/client && yarn lint
        
      - name: Build
        run: cd ./packages/client && yarn build

      - name: Remove build
        run: cd ./packages/client && rm -rf build

