name: Continuous Deployment Master

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy (Master)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: cd ./packages/client && yarn install

      - name: Test
        run: cd ./packages/client && yarn test --watchAll=false

      - name: Lint
        run: cd ./packages/client && yarn lint
        
      - name: Build static files
        run: cd ./packages/client && yarn build --if-present

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.MASTER_NETLIFY_SITE_ID }}
        with: 
          args: deploy --dir=./packages/client/build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
